from .eq_20_band import NODE_CLASS_MAPPINGS as EQ_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as EQ_NAMES
from .eq_slider_pro import NODE_CLASS_MAPPINGS as SLIDER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SLIDER_NAMES  
from .audio_upscaler import NODE_CLASS_MAPPINGS as UPSCALER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as UPSCALER_NAMES
from .audio_resampler import NODE_CLASS_MAPPINGS as RESAMPLER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as RESAMPLER_NAMES
from .audio_denoiser import NODE_CLASS_MAPPINGS as DENOISER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DENOISER_NAMES
from .audio_channel_splitter import NODE_CLASS_MAPPINGS as SPLITTER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SPLITTER_NAMES
from .simple_audio_denoiser import NODE_CLASS_MAPPINGS as SIMPLE_DENOISER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SIMPLE_DENOISER_NAMES

NODE_CLASS_MAPPINGS = {
    **EQ_MAPPINGS, 
    **SLIDER_MAPPINGS, 
    **UPSCALER_MAPPINGS, 
    **RESAMPLER_MAPPINGS, 
    **DENOISER_MAPPINGS, 
    **SPLITTER_MAPPINGS,
    **SIMPLE_DENOISER_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **EQ_NAMES, 
    **SLIDER_NAMES, 
    **UPSCALER_NAMES, 
    **RESAMPLER_NAMES, 
    **DENOISER_NAMES, 
    **SPLITTER_NAMES,
    **SIMPLE_DENOISER_NAMES
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']